# Generated by Django 4.1 on 2022-08-21 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='payees',
        ),
        migrations.AddField(
            model_name='payee',
            name='billId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split_app.bill'),
        ),
    ]
